events {}
http {

  # Round Robin upstream (mặc định của nginx) 
  upstream web_backend {
    server web-frontend-server1:80;
    server web-frontend-server2:80;
    # Nginx tự luân phiên request 1→2→1→2... (Round Robin)
  }

  server {
    listen 80;

    location /stub_status {
      stub_status on;
      allow 127.0.0.1;
      allow 172.0.0.0/8;   # Docker network
      deny all;
  }
    # Load-balanced web frontend
    location / {
      proxy_pass         http://web_backend;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    # Application backend API

    # App API (strip /api/)
    location /api/ {
      proxy_pass         http://application-backend-server:8081/;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
    }
    
    # Student API
    location /student/ {
      proxy_pass http://application-backend-server:8081/student;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
    # Keycloak
    location /auth/ {
      proxy_pass http://authentication-identity-server:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
