networks: { cloud-net: { name: cloud-net } }

services:
  web-frontend-server:
    build: ./web-frontend-server
    image: hotensv/web:dev
    container_name: web-frontend-server
    networks: [cloud-net]
    ports: [ "8080:80" ]
    # export port riêng để test web frontend 8080
    
  web-frontend-server1:
    build: ./web-frontend-server
    container_name: web-frontend-server1
    environment:
      SERVER_INSTANCE: "1"
    networks: [cloud-net]
    # Không expose port riêng — truy cập qua api-gateway port 80

  web-frontend-server2:
    build: ./web-frontend-server
    container_name: web-frontend-server2
    environment:
      SERVER_INSTANCE: "2"
    networks: [cloud-net]

  application-backend-server:
    build: ./application-backend-server
    image: hotensv/app:dev
    container_name: application-backend-server
    networks: [cloud-net]
    ports: [ "8085:8081" ]
    environment:
      OIDC_INTERNAL: "http://authentication-identity-server:8080"
      OIDC_REALM: "realm_52300263"
      OIDC_AUDIENCE: "account"

  relational-database-server:
    image: mariadb:11
    container_name: relational-database-server
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: minicloud
    volumes:
      - ./relational-database-server/init:/docker-entrypoint-initdb.d:ro
    ports: [ "3306:3306" ]
    networks: [cloud-net]

  authentication-identity-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: authentication-identity-server
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports: [ "8081:8080" ]
    restart: unless-stopped
    volumes:
      - ./authentication-identity-server/data:/opt/keycloak/data
    networks: [cloud-net]

  object-storage-server:
    image: minio/minio
    container_name: object-storage-server
    command: ["server","/data","--console-address",":9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./object-storage-server/data:/data
    ports: [ "9000:9000", "9001:9001" ]
    networks: [cloud-net]

  internal-dns-server:
    image: internetsystemsconsortium/bind9:9.18
    container_name: internal-dns-server
    ports: [ "1053:53/udp" ]
    volumes:
      - ./internal-dns-server/named.conf.options:/etc/bind/named.conf.options:ro
      - ./internal-dns-server/named.conf.local:/etc/bind/named.conf.local:ro
      - ./internal-dns-server/db.cloud.local:/etc/bind/db.cloud.local:ro
      - ./internal-dns-server/named.conf:/etc/bind/named.conf:ro
    networks: [cloud-net]

  monitoring-node-exporter-server:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter-server
    ports: [ "9100:9100" ]
    networks: [cloud-net]

  monitoring-prometheus-server:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus-server
    ports: [ "9090:9090" ]
    volumes:
      - ./monitoring-prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [cloud-net]

  monitoring-grafana-dashboard-server:
    image: grafana/grafana:latest
    container_name: monitoring-grafana-dashboard-server
    ports: [ "3000:3000" ]
    volumes:
      - ./monitoring-grafana-dashboard-server/data:/var/lib/grafana
    restart: unless-stopped
    networks: [cloud-net]

  api-gateway-proxy-server:
    image: nginx:stable
    container_name: api-gateway-proxy-server
    depends_on:
      - web-frontend-server1
      - web-frontend-server2
      - application-backend-server
      - authentication-identity-server
    ports: [ "80:80" ]
    volumes:
      - ./api-gateway-proxy-server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: [cloud-net]
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command: ["--nginx.scrape-uri=http://api-gateway-proxy-server:80/stub_status"]
    ports: ["9113:9113"]
    networks: [cloud-net]
    depends_on: [api-gateway-proxy-server]
